name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install deps
      run: |
        sudo apt-get install -y \
            perl perl-modules \
            libyaml-tiny-perl libjson-perl libxml-writer-perl libxml-writer-perl

    - name: validate and build
      run: |
        tools/validate.pl
        cp -a tocalls.yaml generated/

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aprs-deviceid-release
        path: |
            generated
